### 전처리 

In [1]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [2]:
iris_df = pd.read_csv('data/iris.csv')
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        target  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

### Label Encoder
- 문자 데이터가 저장되어 있는 컬럼의 데이터를 숫자로 변환하는 작업을 한다.
- 지정된 컬럼에 저장되어 있는 값들을 확인하고 각 값들에 숫자를 부여해 변환
- 복원도 가능

In [5]:
iris_df['target'].value_counts().index

Index(['setosa', 'versicolor', 'virginica'], dtype='object')

In [6]:
# 저장된 값을 이용해 딕셔너리 생성
dict1 = {
    'virginica' : 0,
    'setosa': 1,
    'versicolor' : 2
}
df_map = iris_df['target'].map(dict1)
print(df_map)

0      1
1      1
2      1
3      1
4      1
      ..
145    0
146    0
147    0
148    0
149    0
Name: target, Length: 150, dtype: int64


In [7]:
dict2 = {
    0 : 'virginica',
    1 : 'setosa',
    2 : 'versicolor'
}
df_map2 = df_map.map(dict2)
print(df_map2)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: target, Length: 150, dtype: object


In [8]:
# LableEncoder
encoder1 = LabelEncoder()
encoder1.fit(iris_df['target'])
df_enc1 = encoder1.transform(iris_df['target'])
df_enc1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
df_enc2 = encoder1.inverse_transform(df_enc1)
df_enc2

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

### 표준화 작업
- 학습 데이터의 각 컬럼의 데이터를 비슷한 수준의 범위로 맞추는 작업
- 성능을 약간 상승시킬 수 있는 효과를 얻을 수 있다.
- 시각화할 때도 도움이 된다.

In [10]:
X = iris_df.drop('target',axis=1)
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [11]:
# 표준화
scaler1 = StandardScaler()

scaler1.fit(X)

# 변환
scaler_df = scaler1.transform(X)
scaler_df

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
# 그래프 설정 
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['font.size'] = 16
plt.rcParams['figure.figsize'] = 20, 10
plt.rcParams['axes.unicode_minus'] = False

In [16]:
# 데이터 전처리 알고리즘
from sklearn.preprocessing  import LabelEncoder
from sklearn.preprocessing  import StandardScaler

In [17]:
# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

In [18]:
# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

In [19]:
iris_df = pd.read_csv('data/iris.csv')
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [27]:
X = iris_df.drop('target', axis=1)
y = iris_df['target']
print(X)
display(y)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]


0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: target, Length: 150, dtype: object

In [21]:
# 문자열 -> 숫자
enc1 = LabelEncoder()
enc1.fit(y)
y = enc1.transform(y)

In [22]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
# 전체 데이터 수
len(X)

150

In [25]:
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size=0.3,
                                                    random_state=1)
print(len(train_X))
print(len(test_X))
train_X

105
45


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
118                7.7               2.6                6.9               2.3
18                 5.7               3.8                1.7               0.3
4                  5.0               3.6                1.4               0.2
45                 4.8               3.0                1.4               0.3
59                 5.2               2.7                3.9               1.4
..                 ...               ...                ...               ...
133                6.3               2.8                5.1               1.5
137                6.4               3.1                5.5               1.8
72                 6.3               2.5                4.9               1.5
140                6.7               3.1                5.6               2.4
37                 4.9               3.6                1.4               0.1

[105 rows x 4 columns]

### 학습과 평가를 진행

In [26]:
from sklearn.linear_model import LogisticRegression

model1 = LogisticRegression()
model1.fit(train_X,train_y)

LogisticRegression()

In [29]:
#학습한 데이터를 통한 검증
# 무조건 성능이 잘나와야 한다.
from sklearn.metrics import accuracy_score

train_pred = model1.predict(train_X)
#평가
r1 = accuracy_score(train_y, train_pred)
r1

0.9809523809523809

In [30]:
# 검증용 데이터(학습 하지 않은 데이터)를 통한 평가
# 학습하지 않은 데이터를 통해 예측 결과를 가져온다.
test_pred = model1.predict(test_X)
#평가
r2 = accuracy_score(test_y, test_pred)
r2

0.9777777777777777

In [33]:
# 사용할 학습 모델을 생성
model2 = LogisticRegression(solver='liblinear')

# 교차 검증을 실시 한다.
# 첫 번째 : 평가해볼 학습 모델
# 두 번째 : 입력데이터
# 세 번째 : 결과 데이터
# scoring : 평가 지표
# cv : 교차 검증 회수 
# 만약 cv를 3으로 줬다면 ... 데이터가 총 3개의 꾸러미로 나뉜다.
# 1 회차 : 1+2 - 학습, 3 - 검증
# 2 회차 : 1+3 - 학습, 2 - 검증
# 3 회차 : 2+3 - 학습, 1 - 검증 
r1 = cross_val_score(model2, X,y, scoring='accuracy', cv=3)
r1

array([0.96, 0.96, 0.94])

### KFold 교차 검증

In [46]:
kfold = KFold(n_splits=3,shuffle=True)
list(kfold.split(X))
#print(X.shape)

[(array([  1,   2,   3,   4,   5,   8,   9,  10,  12,  13,  16,  17,  18,
          22,  24,  26,  27,  30,  31,  32,  33,  34,  35,  36,  37,  38,
          39,  40,  41,  42,  45,  47,  48,  49,  50,  53,  54,  56,  57,
          58,  59,  61,  64,  65,  66,  68,  69,  70,  71,  73,  74,  75,
          78,  79,  81,  82,  83,  84,  86,  87,  88,  89,  90,  91,  93,
          95,  97,  98, 100, 101, 103, 104, 105, 108, 109, 111, 112, 113,
         116, 117, 119, 121, 125, 126, 128, 129, 130, 131, 132, 134, 137,
         138, 139, 142, 143, 145, 146, 147, 148, 149]),
  array([  0,   6,   7,  11,  14,  15,  19,  20,  21,  23,  25,  28,  29,
          43,  44,  46,  51,  52,  55,  60,  62,  63,  67,  72,  76,  77,
          80,  85,  92,  94,  96,  99, 102, 106, 107, 110, 114, 115, 118,
         120, 122, 123, 124, 127, 133, 135, 136, 140, 141, 144])),
 (array([  0,   1,   2,   4,   5,   6,   7,  11,  13,  14,  15,  19,  20,
          21,  22,  23,  25,  26,  27,  28,  29,  30,  31,  32,

In [47]:
model3 = LogisticRegression(solver='liblinear')
r2 = cross_val_score(model3, X,y,scoring='accuracy', cv=kfold)
r2

array([0.98, 0.92, 0.96])

In [49]:
#폴드 생성
kfold1 = KFold(n_splits=3)
kfold2 = KFold(n_splits=3, shuffle=True)
kfold3 = StratifiedKFold(n_splits=3)

In [50]:
# KFold, shuffle : False
for train_idx, test_idx in kfold1.split(X):
    y1 = y[train_idx]
    y2 = y[test_idx]
    
    s1 = pd.Series(y1)
    s2 = pd.Series(y2)
    
    display(s1.value_counts())
    display(s2.value_counts())

versicolor    50
virginica     50
Name: target, dtype: int64

setosa    50
Name: target, dtype: int64

setosa       50
virginica    50
Name: target, dtype: int64

versicolor    50
Name: target, dtype: int64

setosa        50
versicolor    50
Name: target, dtype: int64

virginica    50
Name: target, dtype: int64

In [51]:
# KFold, shuffle : True
for train_idx, test_idx in kfold2.split(X):
    y1 = y[train_idx]
    y2 = y[test_idx]
    
    s1 = pd.Series(y1)
    s2 = pd.Series(y2)
    
    display(s1.value_counts())
    display(s2.value_counts())

setosa        36
virginica     35
versicolor    29
Name: target, dtype: int64

versicolor    21
virginica     15
setosa        14
Name: target, dtype: int64

virginica     35
versicolor    34
setosa        31
Name: target, dtype: int64

setosa        19
versicolor    16
virginica     15
Name: target, dtype: int64

versicolor    37
setosa        33
virginica     30
Name: target, dtype: int64

virginica     20
setosa        17
versicolor    13
Name: target, dtype: int64

In [53]:
# Stractified K Fold
for train_idx, test_idx in kfold3.split(X,y):
    y1 = y[train_idx]
    y2 = y[test_idx]
    
    s1 = pd.Series(y1)
    s2 = pd.Series(y2)
    
    display(s1.value_counts())
    display(s2.value_counts())

virginica     34
setosa        33
versicolor    33
Name: target, dtype: int64

setosa        17
versicolor    17
virginica     16
Name: target, dtype: int64

versicolor    34
setosa        33
virginica     33
Name: target, dtype: int64

setosa        17
virginica     17
versicolor    16
Name: target, dtype: int64

setosa        34
versicolor    33
virginica     33
Name: target, dtype: int64

versicolor    17
virginica     17
setosa        16
Name: target, dtype: int64

In [54]:
model3 = LogisticRegression(solver='liblinear')
r3 = cross_val_score(model3,X,y,scoring='accuracy', cv=kfold3)
r3

array([0.96, 0.96, 0.94])