## 텐서
파이토치 모델 연사을 위해서는 파이토치의 기본 단위를 텐서(tensor)를 사용해야 한다. 텐서는 GPU연산을 가능하게하고 Numpy 배열과 유사하다.

In [2]:
import torch
import numpy as np

x = torch.empty(5,4)
# torch.empty를 통해 크기가 5 x 4인 빈 텐서를 생헝한다.
x

tensor([[-3.1231e+23,  6.4320e-43, -3.1239e+23,  6.4320e-43],
        [-3.1239e+23,  6.4320e-43, -3.1143e+23,  6.4320e-43],
        [-3.1143e+23,  6.4320e-43, -3.1143e+23,  6.4320e-43],
        [-3.1145e+23,  6.4320e-43, -3.1145e+23,  6.4320e-43],
        [-3.1146e+23,  6.4320e-43, -3.1146e+23,  6.4320e-43]])

In [3]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(2)

tensor([0., 0.])

In [5]:
torch.rand(5,6)

tensor([[0.2517, 0.5661, 0.7375, 0.3230, 0.9748, 0.8757],
        [0.7979, 0.3713, 0.2622, 0.1267, 0.1130, 0.1379],
        [0.3968, 0.9448, 0.2126, 0.6750, 0.1084, 0.4998],
        [0.7790, 0.4560, 0.1753, 0.9980, 0.0938, 0.0932],
        [0.5654, 0.1027, 0.5143, 0.2778, 0.4172, 0.9195]])

### 리스트, 넘파이 배열을 텐서로 만들기
torch.tensor()을 통해 텐서로 변환이 가능하다. torch.FloatTensor(), torch.LongTensor()와 같이 구체적인 텐서 타입을 정의할 수 있다.

In [8]:
I = [13,4]
r = np.array([4,56,7])
print(torch.tensor(I))
print(torch.tensor(r))

tensor([13,  4])
tensor([ 4, 56,  7], dtype=torch.int32)


### 텐서의 크기, 타입 연산
.size()는 텐서의 크기를 확인할 수 있으며 자주 사용된다. x.size()는 x텐서의 크기이므로 torch.Size([5,4])로 추력된다. 따라서 x.size()[1]는 4를 출력한다. 혹은 x.size(1)로도 표현이 가능하다.

In [9]:
x.size()[1]

4

In [10]:
type(x)

torch.Tensor

In [11]:
x = torch.rand(2,2) # 2 x 2 랜덤 행렬
y = torch.rand(2,2)

In [13]:
print(torch.add(x,y)) # x+y
print(y.add(x)) # y에 x를 더한다.

tensor([[1.5314, 1.1827],
        [1.4164, 0.5631]])
tensor([[1.5314, 1.1827],
        [1.4164, 0.5631]])


In [14]:
y.add_(x) # y에 x를 더하여 y를 갱신한다.

tensor([[1.5314, 1.1827],
        [1.4164, 0.5631]])

기존의 값을 덮어 씌우는 방식을 인플레이스 방식이라 한다.

### 텐서의 크기 변환

In [15]:
x = torch.rand(8,8)
print(x.size())

torch.Size([8, 8])


In [16]:
a = x.view(64) # 크기를 바꿔줌 8x8 -> 64
print(a.size())

torch.Size([64])


In [17]:
b = x.view(-1,4,4)
print(b.size())

torch.Size([4, 4, 4])


In [18]:
torch.Size([4,4,4])

torch.Size([4, 4, 4])

view는 텐서 크기를 바꿔주는 함수이다 8x8 2차원에서 64 한줄로 변경  
-1은 원래 크기가 되게 하는 값으로 전체 성분이 64개가 되게 하는 4x4x4 배열을 만들어야 한다. -1은 4로 자동으로 할당됨

In [20]:
x = torch.rand(8,8)
y = x.numpy()
type(y)

numpy.ndarray

x = torch.ones(1)
print(x.item())